name: mlglobal
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - dm-tree
  - netcdf4
  - xarray
  - cartopy
  - boto3
  - nceplibs-g2c
  - grib2io
  - jupyterlab
  - pip
  - pip:
    - flax
